package com.compiler.opcodes;

import com.compiler.annotation.OpcodeInfo;

public class Opcodes {
	@OpcodeInfo(num=0)
	public static final byte AALOAD 		= 0x32;
	@OpcodeInfo(num=0)
	public static final byte AASTORE 	= 0x53;
	@OpcodeInfo(num=0)
	public static final byte ACONST_NULL = 0x01;
	@OpcodeInfo(num=1)
	public static final byte ALOAD 		= 0x19;
	@OpcodeInfo(num=0)
	public static final byte ALOAD_0		= 0x2a;
	@OpcodeInfo(num=0)
	public static final byte ALOAD_1		= 0x2b;
	@OpcodeInfo(num=0)
	public static final byte ALOAD_2		= 0x2c;
	@OpcodeInfo(num=0)
	public static final byte ALOAD_3		= 0x2d;
	@OpcodeInfo(num=2, type=1)
	public static final byte ANEWARRAY	= (byte) 0xbd;
	@OpcodeInfo(num=0)
	public static final byte ARETURN		= (byte) 0xb0;
	@OpcodeInfo(num=0)
	public static final byte ARRAYLENGTH	= (byte) 0xbe;
	@OpcodeInfo(num=1)
	public static final byte ASTORE		= 0x3a;
	@OpcodeInfo(num=0)
	public static final byte ASTORE_0	= 0x4b;
	@OpcodeInfo(num=0)
	public static final byte ASTORE_1	= 0x4c;
	@OpcodeInfo(num=0)
	public static final byte ASTORE_2	= 0x4d;
	@OpcodeInfo(num=0)
	public static final byte ASTORE_3	= 0x4e;
	@OpcodeInfo(num=0)
	public static final byte ATHROW		= (byte) 0xbf;
	@OpcodeInfo(num=0)
	public static final byte BALOAD		= 0x33;
	@OpcodeInfo(num=0)
	public static final byte BASTORE		= 0x54;
	@OpcodeInfo(num=1)
	public static final byte BIPUSH		= 0x10;
	@OpcodeInfo(num=0)
	public static final byte CALOAD		= 0x34;
	@OpcodeInfo(num=0)
	public static final byte CASTORE		= 0x55;
	@OpcodeInfo(num=2, type=1)
	public static final byte CHECKCAST	= (byte) 0xc0;
	@OpcodeInfo(num=0)
	public static final byte D2F			= (byte) 0x90;
	@OpcodeInfo(num=0)
	public static final byte D2I			= (byte) 0x8e;
	@OpcodeInfo(num=0)
	public static final byte D2L			= (byte) 0x8f;
	@OpcodeInfo(num=0)
	public static final byte DADD		= 0x63;
	@OpcodeInfo(num=0)
	public static final byte DALOAD		= 0x31;
	@OpcodeInfo(num=0)
	public static final byte DASTORE		= 0x52;
	@OpcodeInfo(num=0)
	public static final byte DCMPG		= (byte) 0x98;
	@OpcodeInfo(num=0)
	public static final byte DCMPL		= (byte) 0x97;
	@OpcodeInfo(num=0)
	public static final byte DCONST_0	= 0x0e;
	@OpcodeInfo(num=0)
	public static final byte DCONST_1	= 0x0f;
	@OpcodeInfo(num=0)
	public static final byte DDIV		= 0x6f;
	@OpcodeInfo(num=1)
	public static final byte DLOAD		= 0x18;
	@OpcodeInfo(num=0)
	public static final byte DLOAD_0		= 0x26;
	@OpcodeInfo(num=0)
	public static final byte DLOAD_1		= 0x27;
	@OpcodeInfo(num=0)
	public static final byte DLOAD_2		= 0x28;
	@OpcodeInfo(num=0)
	public static final byte DLOAD_3		= 0x29;
	@OpcodeInfo(num=0)
	public static final byte DMUL		= 0x6b;
	@OpcodeInfo(num=0)
	public static final byte DNEG		= 0x77;
	@OpcodeInfo(num=0)
	public static final byte DREM		= 0x73;
	@OpcodeInfo(num=0)
	public static final byte DRETURN		= (byte) 0xaf;
	@OpcodeInfo(num=1)
	public static final byte DSTORE		= 0x39;
	@OpcodeInfo(num=0)
	public static final byte DSTORE_0	= 0x47;
	@OpcodeInfo(num=0)
	public static final byte DSTORE_1	= 0x48;
	@OpcodeInfo(num=0)
	public static final byte DSTORE_2	= 0x49;
	@OpcodeInfo(num=0)
	public static final byte DSTORE_3 	= 0x4a;
	@OpcodeInfo(num=0)
	public static final byte DSUB		= 0x67;
	@OpcodeInfo(num=0)
	public static final byte DUP			= 0x59;
	@OpcodeInfo(num=0)
	public static final byte DUP_X1		= 0x5a;
	@OpcodeInfo(num=0)
	public static final byte DUP_X2		= 0x5b;
	@OpcodeInfo(num=0)
	public static final byte DUP2		= 0x5c;
	@OpcodeInfo(num=0)
	public static final byte DUP2_X1		= 0x5d;
	@OpcodeInfo(num=0)
	public static final byte DUP2_X2		= 0x5e;
	@OpcodeInfo(num=0)
	public static final byte F2D			= (byte) 0x8d;
	@OpcodeInfo(num=0)
	public static final byte F2I			= (byte) 0x8b;
	@OpcodeInfo(num=0)
	public static final byte F2L			= (byte) 0x8c;
	@OpcodeInfo(num=0)
	public static final byte FADD		= 0x62;
	@OpcodeInfo(num=0)
	public static final byte FALOAD		= 0x30;
	@OpcodeInfo(num=0)
	public static final byte FASTORE		= 0x51;
	@OpcodeInfo(num=0)
	public static final byte FCMPG		= (byte) 0x96;
	@OpcodeInfo(num=0)
	public static final byte FCMPL		= (byte) 0x95;
	@OpcodeInfo(num=0)
	public static final byte FCONST_0	= 0x0b;
	@OpcodeInfo(num=0)
	public static final byte FCONST_1	= 0x0c;
	@OpcodeInfo(num=0)
	public static final byte FCONST_2	= 0x0d;
	@OpcodeInfo(num=0)
	public static final byte FDIV		= 0x6e;
	@OpcodeInfo(num=1)
	public static final byte FLOAD		= 0x17;
	@OpcodeInfo(num=0)
	public static final byte FLOAD_0		= 0x22;
	@OpcodeInfo(num=0)
	public static final byte FLOAD_1		= 0x23;
	@OpcodeInfo(num=0)
	public static final byte FLOAD_2		= 0x24;
	@OpcodeInfo(num=0)
	public static final byte FLOAD_3		= 0x25;
	@OpcodeInfo(num=0)
	public static final byte FMUL		= 0x6a;
	@OpcodeInfo(num=0)
	public static final byte FNEG		= 0x76;
	@OpcodeInfo(num=0)
	public static final byte FREM		= 0x72;
	@OpcodeInfo(num=0)
	public static final byte FRETURN		= (byte) 0xae;
	@OpcodeInfo(num=1)
	public static final byte FSTORE		= 0x38;
	@OpcodeInfo(num=0)
	public static final byte FSTORE_0 	= 0x43;
	@OpcodeInfo(num=0)
	public static final byte FSTORE_1	= 0x44;
	@OpcodeInfo(num=0)
	public static final byte FSTORE_2	= 0x45;
	@OpcodeInfo(num=0)
	public static final byte FSTORE_3	= 0x46;
	@OpcodeInfo(num=0)
	public static final byte FSUB		= 0x66;
	@OpcodeInfo(num=2, type=1)
	public static final byte GETFIELD	= (byte) 0xb4;
	@OpcodeInfo(num=2, type=1)
	public static final byte GETSTATIC	= (byte) 0xb2;
	@OpcodeInfo(num=2)
	public static final byte GOTO		= (byte) 0xa7;
	@OpcodeInfo(num=4)
	public static final byte GOTO_W		= (byte) 0xc8;
	@OpcodeInfo(num=0)
	public static final byte I2B			= (byte) 0x91;
	@OpcodeInfo(num=0)
	public static final byte I2C			= (byte) 0x92;
	@OpcodeInfo(num=0)
	public static final byte I2D			= (byte) 0x87;
	@OpcodeInfo(num=0)
	public static final byte I2F			= (byte) 0x86;
	@OpcodeInfo(num=0)
	public static final byte I2L			= (byte) 0x85;
	@OpcodeInfo(num=0)
	public static final byte I2S			= (byte) 0x93;
	@OpcodeInfo(num=0)
	public static final byte IADD		= 0x60;
	@OpcodeInfo(num=0)
	public static final byte IALOAD		= 0x2e;
	@OpcodeInfo(num=0)
	public static final byte IAND		= 0x7e;
	@OpcodeInfo(num=0)
	public static final byte IASTORE		= 0x4f;
	@OpcodeInfo(num=0)
	public static final byte ICONST_m1 	= 0x02;
	@OpcodeInfo(num=0)
	public static final byte ICONST_0	= 0x03;
	@OpcodeInfo(num=0)
	public static final byte ICONST_1	= 0x04;
	@OpcodeInfo(num=0)
	public static final byte ICONST_2	= 0x05;
	@OpcodeInfo(num=0)
	public static final byte ICONST_3	= 0x06;
	@OpcodeInfo(num=0)
	public static final byte ICONST_4	= 0x07;
	@OpcodeInfo(num=0)
	public static final byte ICONST_5	= 0x08;
	@OpcodeInfo(num=0)
	public static final byte IDIV		= 0x6c;
	@OpcodeInfo(num=2)
	public static final byte IF_ACMPEQ	= (byte) 0xa5;
	@OpcodeInfo(num=2)
	public static final byte IF_ACMPNE	= (byte) 0xa6;
	@OpcodeInfo(num=2)
	public static final byte IF_ICMPEQ	= (byte) 0x9f;
	@OpcodeInfo(num=2)
	public static final byte IF_ICMPNE	= (byte) 0xa0;
	@OpcodeInfo(num=2)
	public static final byte IF_ICMPLT	= (byte) 0xa1;
	@OpcodeInfo(num=2)
	public static final byte IF_ICMPGE	= (byte) 0xa2;
	@OpcodeInfo(num=2)
	public static final byte IF_ICMPGT	= (byte) 0xa3;
	@OpcodeInfo(num=2)
	public static final byte IF_ICMPLE	= (byte) 0xa4;
	@OpcodeInfo(num=2)
	public static final byte IFEQ		= (byte) 0x99;
	@OpcodeInfo(num=2)
	public static final byte IFNE		= (byte) 0x9a;
	@OpcodeInfo(num=2)
	public static final byte IFLT		= (byte) 0x9b;
	@OpcodeInfo(num=2)
	public static final byte IFGE		= (byte) 0x9c;
	@OpcodeInfo(num=2)
	public static final byte IFGT		= (byte) 0x9d;
	@OpcodeInfo(num=2)
	public static final byte IFLE		= (byte) 0x9e;
	@OpcodeInfo(num=2)
	public static final byte IFNONNULL	= (byte) 0xc7;
	@OpcodeInfo(num=2)
	public static final byte IFNULL		= (byte) 0xc6;
	@OpcodeInfo(num=2)
	public static final byte IINC		= (byte) 0x84;
	@OpcodeInfo(num=1)
	public static final byte ILOAD		= 0x15;
	@OpcodeInfo(num=0)
	public static final byte ILOAD_0		= 0x1a;
	@OpcodeInfo(num=0)
	public static final byte ILOAD_1		= 0x1b;
	@OpcodeInfo(num=0)
	public static final byte ILOAD_2		= 0x1c;
	@OpcodeInfo(num=0)
	public static final byte ILOAD_3		= 0x1d;
	@OpcodeInfo(num=0)
	public static final byte IMUL		= 0x68;
	@OpcodeInfo(num=0)
	public static final byte INEG		= 0x74;
	@OpcodeInfo(num=2, type=1)
	public static final byte INSTANCEOF	= (byte) 0xc1;
	@OpcodeInfo(num=4, type=1)
	public static final byte INVOKEDYNAMIC	= (byte) 0xba;
	@OpcodeInfo(num=4, type=1)
	public static final byte INVOKEINTERFACE	= (byte) 0xb9;
	@OpcodeInfo(num=2, type=1)
	public static final byte INVOKESPECIAL	= (byte) 0xb7;
	@OpcodeInfo(num=2, type=1)
	public static final byte INVOKESTATIC	= (byte) 0xb8;
	@OpcodeInfo(num=2, type=1)
	public static final byte INVOKEVIRTUAL	= (byte) 0xb6;
	@OpcodeInfo(num=0)
	public static final byte IOR			= (byte) 0x80;
	@OpcodeInfo(num=0)
	public static final byte IREM		= 0x70;
	@OpcodeInfo(num=0)
	public static final byte IRETURN		= (byte) 0xac;
	@OpcodeInfo(num=0)
	public static final byte ISHL		= 0x78;
	@OpcodeInfo(num=0)
	public static final byte ISHR		= 0x7a;
	@OpcodeInfo(num=1)
	public static final byte ISTORE		= 0x36;
	@OpcodeInfo(num=0)
	public static final byte ISTORE_0 	= 0x3b;
	@OpcodeInfo(num=0)
	public static final byte ISTORE_1	= 0x3c;
	@OpcodeInfo(num=0)
	public static final byte ISTORE_2	= 0x3d;
	@OpcodeInfo(num=0)
	public static final byte ISTORE_3	= 0x3e;
	@OpcodeInfo(num=0)
	public static final byte ISUB		= 0x64;
	@OpcodeInfo(num=0)
	public static final byte IUSHR		= 0x7c;
	@OpcodeInfo(num=0)
	public static final byte IXOR		= (byte) 0x82;
	@OpcodeInfo(num=2)
	public static final byte JSR			= (byte) 0xa8;
	@OpcodeInfo(num=4)
	public static final byte JSR_W		= (byte) 0xc9;
	@OpcodeInfo(num=0)
	public static final byte L2D			= (byte) 0x8a;
	@OpcodeInfo(num=0)
	public static final byte L2F			= (byte) 0x89;
	@OpcodeInfo(num=0)
	public static final byte L2I			= (byte) 0x88;
	@OpcodeInfo(num=0)
	public static final byte LADD		= 0x61;
	@OpcodeInfo(num=0)
	public static final byte LALOAD		= 0x2f;
	@OpcodeInfo(num=0)
	public static final byte LAND		= 0x7f;
	@OpcodeInfo(num=0)
	public static final byte LASTORE		= 0x50;
	@OpcodeInfo(num=0)
	public static final byte LCMP		= (byte) 0x94;
	@OpcodeInfo(num=0)
	public static final byte LCONST_0	= 0x09;
	@OpcodeInfo(num=0)
	public static final byte LCONST_1	= 0x0a;
	@OpcodeInfo(num=1, type=1)
	public static final byte LDC			= 0x12;
	@OpcodeInfo(num=2, type=1)
	public static final byte LDC_W		= 0x13;
	@OpcodeInfo(num=2, type=1)
	public static final byte LDC2_W		= 0x14;
	@OpcodeInfo(num=0)
	public static final byte LDIV		= 0x6d;
	@OpcodeInfo(num=1)
	public static final byte LLOAD		= 0x16;
	@OpcodeInfo(num=0)
	public static final byte LLOAD_0		= 0x1e;
	@OpcodeInfo(num=0)
	public static final byte LLOAD_1		= 0x1f;
	@OpcodeInfo(num=0)
	public static final byte LLOAD_2		= 0x20;
	@OpcodeInfo(num=0)
	public static final byte LLOAD_3		= 0x21;
	@OpcodeInfo(num=0)
	public static final byte LMUL		= 0x69;
	@OpcodeInfo(num=0)
	public static final byte LNEG		= 0x75;
	public static final byte LOOKUPSWITCH	= (byte) 0xab;
	@OpcodeInfo(num=0)
	public static final byte LOR			= (byte) 0x81;
	@OpcodeInfo(num=0)
	public static final byte LREM		= 0x71;
	@OpcodeInfo(num=0)
	public static final byte LRETURN		= (byte) 0xad;
	@OpcodeInfo(num=0)
	public static final byte LSHL		= 0x79;
	@OpcodeInfo(num=0)
	public static final byte LSHR		= 0x7b;
	@OpcodeInfo(num=1)
	public static final byte LSTORE		= 0x37;
	@OpcodeInfo(num=0)
	public static final byte LSTORE_0	= 0x3f;
	@OpcodeInfo(num=0)
	public static final byte LSTORE_1	= 0x40;
	@OpcodeInfo(num=0)
	public static final byte LSTORE_2	= 0x41;
	@OpcodeInfo(num=0)
	public static final byte LSTORE_3	= 0x42;
	@OpcodeInfo(num=0)
	public static final byte LSUB		= 0x65;
	@OpcodeInfo(num=0)
	public static final byte LUSHR		= 0x7d;
	@OpcodeInfo(num=0)
	public static final byte LXOR		= (byte) 0x83;
	@OpcodeInfo(num=0)
	public static final byte MONITORENTER	= (byte) 0xc2;
	@OpcodeInfo(num=0)
	public static final byte MONITOREXIT	= (byte) 0xc3;
	@OpcodeInfo(num=3, type=1)
	public static final byte MULTIANEWARRAY	= (byte) 0xc5;
	@OpcodeInfo(num=2, type=1)
	public static final byte NEW			= (byte) 0xbb;
	@OpcodeInfo(num=1)
	public static final byte NEWARRAY	= (byte) 0xbc;
	@OpcodeInfo(num=0)
	public static final byte NOP			= 0x00;
	@OpcodeInfo(num=0)
	public static final byte POP			= 0x57;
	@OpcodeInfo(num=0)
	public static final byte POP2		= 0x58;
	@OpcodeInfo(num=2, type=1)
	public static final byte PUTFIELD	= (byte) 0xb5;
	@OpcodeInfo(num=2, type=1)
	public static final byte PUTSTATIC	= (byte) 0xb3;
	@OpcodeInfo(num=1)
	public static final byte RET			= (byte) 0xa9;
	@OpcodeInfo(num=0)
	public static final byte RETURN		= (byte) 0xb1;
	@OpcodeInfo(num=0)
	public static final byte SALOAD		= 0x35;
	@OpcodeInfo(num=0)
	public static final byte SASTORE		= 0x56;
	@OpcodeInfo(num=2)
	public static final byte SIPUSH		= 0x11;
	@OpcodeInfo(num=0)
	public static final byte SWAP		= 0x5f;
	public static final byte TABLESWITCH	= (byte) 0xaa;
	public static final byte WIDE		= (byte) 0xc4;
	
}
